version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: med-postgres
    environment:
      POSTGRES_USER: med
      POSTGRES_PASSWORD: med
      POSTGRES_DB: med
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U med']
      interval: 5s
      retries: 10

  backend-auth:
    build:
      context: .
      dockerfile: apps/backend-auth/Dockerfile
    container_name: med-backend-auth
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: med
      DB_PASS: med
      DB_NAME: med
      JWT_SECRET: super-secret-change-me
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy

  backend-api:
    build:
      context: .
      dockerfile: apps/backend-api/Dockerfile
    container_name: med-backend-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: med
      DB_PASS: med
      DB_NAME: med
      JWT_SECRET: super-secret-change-me
    ports:
      - '4001:4001'
    depends_on:
      postgres:
        condition: service_healthy

  mfe-appointments:
    build:
      context: .
      dockerfile: apps/mfe-appointments/Dockerfile
    container_name: med-mfe-appointments

  mfe-medcard:
    build:
      context: .
      dockerfile: apps/mfe-medcard/Dockerfile
    container_name: med-mfe-medcard

  frontend:
    build:
      context: .
      dockerfile: apps/frontend-host/Dockerfile
    container_name: med-frontend
    ports:
      - '80:80'
    depends_on:
      - backend-auth
      - backend-api
      - mfe-appointments
      - mfe-medcard

volumes:
  pgdata:
