server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/auth/ {
    proxy_pass http://backend-auth:4000/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/appointments {
    proxy_pass http://backend-api:4001/appointments;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/records {
    proxy_pass http://backend-api:4001/records;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /appointments/ {
    proxy_pass http://mfe-appointments;
    proxy_set_header Host $host;
    proxy_intercept_errors on;
    error_page 502 503 504 = @mfe_unavailable;
  }

  location /medcard/ {
    proxy_pass http://mfe-medcard;
    proxy_set_header Host $host;
    proxy_intercept_errors on;
    error_page 502 503 504 = @mfe_unavailable;
  }

  location @mfe_unavailable {
    return 503 'micro-frontend unavailable';
    add_header Content-Type text/plain;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
