server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /appointments/ {
    alias /usr/share/nginx/html/appointments/;
    try_files $uri $uri/ /appointments/index.html;
    add_header Access-Control-Allow-Origin *;
  }

  location /medcard/ {
    alias /usr/share/nginx/html/medcard/;
    try_files $uri $uri/ /medcard/index.html;
    add_header Access-Control-Allow-Origin *;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
